### PR TITLE
Dynamic Progress Bar

### PR DESCRIPTION
**Pull request by jeff-hernandez**
This PR renders the name of the labeling function in the progress bar.

```
Elapsed: 00:00 | Remaining: 00:00 | Progress: 100%|████| Calculated: 5/5 my_labels
```

### CODE REVIEW

**Comment by kmax12** [comment]
i think this should be the value of target_entity. because that is what we are iterating over

**Comment by jeff-hernandez** [comment]
I updated to render target entity.
```
Elapsed: 00:00 | Remaining: 00:00 | Progress: 100%|██| Calculated: 5/5 customer_id
```

**Comment by jeff-hernandez** [comment]
What do you think about this rendering?

```
Elapsed: 00:00 | Remaining: 00:00 | Progress: 100%|██| CUSTOMER_ID: 5/5 
```

**Comment by kmax12** [comment]
what changed? just the move to all caps? 

i think keep it in the same capitalization as the input

**Comment by jeff-hernandez** [comment]
Yes, also replaced `Calculated`. Okay, I will update to this format.

```
Elapsed: 00:00 | Remaining: 00:00 | Progress: 100%|██| customer_id: 5/5
```

**Pull request merged**
